# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Knowing Less"
license = "Apache-2.0"
licenselink = "https://github.com/LGiki/hugo-theme-knowing-less/blob/master/LICENSE.md"
description = "A HUGO theme for podcasts"
homepage = "https://github.com/LGiki/hugo-theme-knowing-less"
tags = ["responsive", "podcast", "simple", "clean", "blog", "syntax highlighting"]
features = ["responsive", "podcast", "simple", "clean", "blog", "syntax highlighting"]
min_version = "0.64.0"

[author]
  name = "LGiki"
  homepage = "https://github.com/LGiki/"
